name: release

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - 'papers/**'
      - 'rfcs/**'
      - '*.md'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    name: ${{matrix.os}}
    runs-on: ${{matrix.os}}-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cmake . -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: cmake --build . --target Luau.Repl.CLI Luau.Analyze.CLI --config Release
    - uses: actions/upload-artifact@v2
      if: matrix.os != 'windows'
      with:
        name: luau-${{matrix.os}}
        path: luau*
    - uses: actions/upload-artifact@v2
      if: matrix.os == 'windows'
      with:
        name: luau-${{matrix.os}}
        path: Release\luau*.exe
  web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup emsdk
      uses: mymindstorm/setup-emsdk@v9
      with:
        version: 1.38.40
        actions-cache-folder: 'emsdk-cache'
    - name: verify emsdk
      run: |
        emcc -v # verify emscripten installed successfully
    - name: cmake configure
      run: |
        emcmake cmake .
    - name: build
      run: |
        cmake --build . --target Luau.Repl.CLI --config Debug # as seen above but only Repl.CLI.
    - uses: actions/upload-artifact@v2
      with:
        name: luau.wasm
        path: docs/assets/luau/luau.wasm
        if-no-files-found: error
    - uses: actions/upload-artifact@v2
      with:
        name: luau.js
        path: docs/assets/luau/luau.js
        if-no-files-found: error